version: '3'

services:
  aws:
    image: localstack/localstack
    ports:
      - 4566:4566
      - '4510-4559:4510-4559'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - COMPOSE_CONVERT_WINDOWS_PATHS=1
  cognito:
    image: jagregory/cognito-local
    ports:
      - 9229:9229
    volumes:
      - ./data/cognito:/app/.cognito
  api-gateway:
    build: .
    ports:
      - 9000:9000
  api-gateway-swagger:
    image: swaggerapi/swagger-ui
    ports:
      - 9001:8080
    environment:
      - SWAGGER_JSON=/tmp/api-gateway.yml
    volumes:
      - ./api-gateway.yml:/tmp/api-gateway.yml:ro
